name: CrystalCore
version: '${project.version}'
main: net.web1337.borhani.crystalCore.CrystalCore
api-version: '1.20'
description: Crystal PvP optimization plugin for high-ping players
website: https://modrinth.com/plugin/crystalcore
authors:
  - borhani
dependencies:
  server:
    ProtocolLib:
      load: BEFORE
      required: true